### ISSUE TITLE
I'd love to help on this. 

### ISSUE THREAD

**Issue by okkebal** [openzim/wikihow#1]
Hi,

I am really interested in getting Wikihow to Kiwix. A don't think I can start from scratch though. Any plans on starting this project?

Let me know when I can help.

**Comment by ISNIT0** [comment]
If you want, I can do a Skype call with you and walk through what we already have?

**Comment by okkebal** [comment]
I saw somewhere it is based on mwoffliner. I guess I'll take a look at that first. I've just worked on Sotoki, but that is Python and very different from mwoffliner. I see MWoffliner uses JS and Node. The code there seems pretty readable. 

I have some experience with JS, but not with Node. I guess I'll spend most of my time trying to install mwoffliner. I am really bad at these Linux installs. Take a look how much effort it was before I got Sotoki running: https://github.com/openzim/sotoki/issues/57

I am using this "zimmaker" VM now. Its pretty nice.

Once I can change code and run the app, I'm fine. 

Am I correct, or is Wikihow based on something else?

I try to install that first, see how far I get. Try to understand what it does, and then do a Skype call with you. That way I know a bit what we are talking about beforehand.

**Comment by ISNIT0** [comment]
We did use mwoffliner, but because of the version of MediaWiki that wikihow uses, it won't behave as it should.

I believe @kelson42 and I agreed this needed it's own scraper.

I've got some code somewhere locally that is a start, but I'll need to dig it out and see what needs doing.

I'm hoping to pull some of the logic from https://github.com/openzim/phet into a separate module and use that in this scraper.

**Comment by kelson42** [comment]
@ISNIT0 @okkebal WikiHow uses Mediawiki so we thought we could mwoffliner. But it looks like WH has many particularities (@ISNIT0 knows the details). The ideal solution would to use mwoffliner library as a base but build on the top of it the necessary handling of that particularities. That is why I have created a dedicated git repo for it. https://github.com/openzim/wikihow. @ISNIT0 could maybe upload his stub there and then the dicussion could continue (there too)?
