### ISSUE TITLE
Polishing

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#10]
- Finalize metadata, U.I polishing, etc.
- Finalize scraper behavior and logging.

TBD

**Comment by kelson42** [comment]
The scraper should report aboit its progress, which is not the case for the moment.

**Comment by rgaudin** [comment]
I think points above are already covered.

Another important point is to ensure the ZIM works fine on mobile devices. We fixed a few visual issues in CSS due to some wikihow weirdness ; those might require media queries to adapt to screen sizes.

**Comment by fadiga** [comment]
![IMG_5913](https://user-images.githubusercontent.com/354071/132954415-306f261a-f6ba-4a40-83be-7cb69b5a4eca.PNG)
![IMG_5914](https://user-images.githubusercontent.com/354071/132954423-3ab0a849-9a43-4dcd-a778-5d2141b389e6.PNG)
![IMG_5915](https://user-images.githubusercontent.com/354071/132954433-54017d74-f583-47af-b52a-4642e69951eb.PNG)
![IMG_5916](https://user-images.githubusercontent.com/354071/132954439-e7cc3b69-025b-4020-9cf4-39ba81560e7c.PNG)
![IMG_5922](https://user-images.githubusercontent.com/354071/132954443-3866cd36-9832-4b2f-a2d0-120b6dfed6b3.PNG)
![IMG_5921](https://user-images.githubusercontent.com/354071/132954445-86bad165-7f8d-48b8-9986-392556db8fbf.PNG)
![IMG_5920](https://user-images.githubusercontent.com/354071/132954447-e2f5ed32-f806-44bc-ab51-1310483ec679.PNG)
![IMG_5919](https://user-images.githubusercontent.com/354071/132954455-884b0ad7-882d-4264-b9b4-74aad9fafeb1.PNG)
![IMG_5918](https://user-images.githubusercontent.com/354071/132954457-d0dacd97-9ac5-4220-bad5-080a8f1b6a51.PNG)
