### ISSUE TITLE
Remove advertisement widget

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#100]
See at https://fr.wikihow.com/faire-du-d%C3%A9sinfectant-pour-les-mains#quick_summary_section on the right sidebar.

**Comment by MrTechHunter** [comment]
Hi mate 🙂,
Do you mean this?
![wiki](https://user-images.githubusercontent.com/59443165/135750945-aec0c4f8-18f2-4dea-960b-a4b2a0f7305d.jpg)

**Comment by MrTechHunter** [comment]
great, good luck! 👍

**Comment by kelson42** [comment]
Sorry, the ticket was invalid.

**Comment by MrTechHunter** [comment]
No problem. Don't worry about it. 😊
