### ISSUE TITLE
WikiHow zim files are definitely not using the correct logos / icons

### ISSUE THREAD

**Issue by Popolechien** [openzim/wikihow#104]
![Screenshot wikiHow](https://user-images.githubusercontent.com/21675885/143431429-ad04ce42-6859-4fdf-ab00-0b270533edf3.png)

**Comment by rgaudin** [comment]
Shouldn't it be in wikihow repo ?

**Comment by rgaudin** [comment]
It's probably because wikihow ZIMs uses new Illustration and no favicon

**Comment by rgaudin** [comment]
So I'd say it's a reader issue

**Comment by rgaudin** [comment]
Sorry you'll have to move it again

**Comment by Popolechien** [comment]
Could we fix it by forcing the wikiHow logo into the recipe?

**Comment by Popolechien** [comment]
Not sure how much of a reader issue that is: I'm looking at library.kiwix.org (kiwix-serve) and the WikiHow zim files show no icon at all.
![Capture d’écran 2021-11-25 à 12 19 56](https://user-images.githubusercontent.com/21675885/143432383-9bfb1a4a-7ae9-4691-aa15-fdf655734c6e.png)

**Comment by rgaudin** [comment]
> Could we fix it by forcing the wikiHow logo into the recipe?

No. The scraper already gets the proper icon and sets it properly. It's a *new ZIM*, using the new `Illustration_` metadata for the Icon. The problem is that the reader, which uses previous version is not aware of this. You'll notice that _old_ kiwix-serve doesn't displays it either while the current one (on dev-library) does.

**Comment by Popolechien** [comment]
@kelson42 Not sure we can move the issue across projects (from openzim/wikihow to kiwix/kiwix-android)

**Comment by kelson42** [comment]
Which ZIM file is that? Do we know if this is a problem in the `library.xml` or in Kiwix-Android?

**Comment by rgaudin** [comment]
> Which ZIM file is that? Do we know if this is a problem in the `library.xml` or in Kiwix-Android?

have you read my comments ?

**Comment by kelson42** [comment]
@rgaudin yes, even 3 times now and my question stay unanswered. I need the exact filename to make my assessment.

**Comment by Popolechien** [comment]
@kelson42 There has only been one run so the files and file names are those in https://download.kiwix.org/zim/wikihow/

wikihow_pt_maxi_2021-10.zim
wikihow_nl_maxi_2021-10.zim
wikihow_es_maxi_2021-10.zim 
wikihow_ko_maxi_2021-10.zim

Interestingly, here is another screenshot of the same series taken at a different time - the icons have changed compared to my earlier screenshot:
![Screenshot_20211125-223320](https://user-images.githubusercontent.com/21675885/143501745-4561fe2e-a4dc-4f09-b2b3-d53310c5380e.png)

**Comment by kelson42** [comment]
@Popolechien thx.

**Comment by kelson42** [comment]
For some reason this ticket does not move... but it should. Config looks good.

**Comment by rgaudin** [comment]
> @rgaudin yes, even 3 times now and my question stay unanswered. I need the exact filename to make my assessment.

I don't know what else to say. Those ZIM have `Illustration_48x48` and thus no `-/favicon` entry. The library XML doesn't exposes those icons so there is no `favicon` property in those nodes.

kiwix-serve 3.1.2-5 understands there is no icon and thus displays no icon. We're aware of this ; it was discussed back in August. kiwix-android apparently isn't expecting this situation and is probably displaying an icon from the next/previous available node. 

Possible immediate fix: change the tool that generates the library.xml so it sets the favicon property from Illustration if there's no `-/favicon`.

FYI, libzim7 (at least pylibzim) doesn't allow specifying a namespace so we can't add a `-/favicon` entry to those ZIM, should we want to.

**Comment by kelson42** [comment]
I will move the ticket to kiwix/kiwix-android
