### ISSUE TITLE
Stuck on "ensuring source site dom integrity" when command run

### ISSUE THREAD

**Issue by Adam7288** [openzim/wikihow#107]
language = en
stuck for 10 hours no progress
ctrl-d does nothing
have to open separate terminal and issue docker container stop command to actually exit

**Comment by kelson42** [comment]
@Adam7288 please share your exact command and the last 100 lines of the log would be helpful.

**Comment by rgaudin** [comment]
Thanks ; I can not reproduce.

Can you please share the complete command you used? Using `--debug` you would get additional output that may lead to another cause.

In the mean time, you can also try the `--skip-dom-check` param.

**Comment by Adam7288** [comment]
root@docker1:~# docker run -v /truenas/wiki:/output openzim/wikihow wikihow2zim                                 --language en --debug
[MainThread::2021-12-29 19:19:51,070] INFO:Starting scraper with:
  language: English (www.wikihow.com)
  output_dir: /output
  build_dir: /www.wikihow.com_v_sqqvex
  categories: all
[MainThread::2021-12-29 19:19:51,070] INFO:Ensuring source site DOM Integrity
[MainThread::2021-12-29 19:19:51,070] DEBUG:> checking CategoryListing
[MainThread::2021-12-29 19:19:51,292] DEBUG:> checking Category Page
[MainThread::2021-12-29 19:19:53,344] DEBUG:> checking Article Page
[MainThread::2021-12-29 19:19:53,535] DEBUG:Fecthing website metdata
[MainThread::2021-12-29 19:19:53,857] DEBUG:homepage_name: Main-Page
category_prefix: Category
url_special_category: Special:CategoryListing
dir: ltr
title: wikiHow: How-to instructions you can trust.
description: Learn how to do anything with wikiHow, the world's most popular how                                -to website. Easy, well-researched, and trustworthy instructions for everything                                 you want to know.
icon: https://www.wikihow.com/skins/WikiHow/wH-initials_152x152.png
favicon: https://www.wikihow.com/favicon.ico
logo: https://www.wikihow.com/skins/owl/images/wikihow_logo_intl.png
[MainThread::2021-12-29 19:19:53,857] DEBUG:Checking user-provided metadata
[MainThread::2021-12-29 19:19:53,857] DEBUG:Starting Zim creation

**Comment by Adam7288** [comment]
skip check fails at same step:

docker run -v /truenas/wiki:/output openzim/wikihow wikihow2zim --language en --debug --skip-dom-check
[MainThread::2021-12-29 19:31:13,746] INFO:Starting scraper with:
  language: English (www.wikihow.com)
  output_dir: /output
  build_dir: /www.wikihow.com_8su1e2h0
  categories: all
[MainThread::2021-12-29 19:31:13,746] DEBUG:Fecthing website metdata
[MainThread::2021-12-29 19:31:14,072] DEBUG:homepage_name: Main-Page
category_prefix: Category
url_special_category: Special:CategoryListing
dir: ltr
title: wikiHow: How-to instructions you can trust.
description: Learn how to do anything with wikiHow, the world's most popular how-to website. Easy, well-researched, and trustworthy instructions for everything you want to know.
icon: https://www.wikihow.com/skins/WikiHow/wH-initials_152x152.png
favicon: https://www.wikihow.com/favicon.ico
logo: https://www.wikihow.com/skins/owl/images/wikihow_logo_intl.png
[MainThread::2021-12-29 19:31:14,072] DEBUG:Checking user-provided metadata
[MainThread::2021-12-29 19:31:14,072] DEBUG:Starting Zim creation

**Comment by rgaudin** [comment]
Hum, I can't reproduce with the exact same command (except the volume binding of course). The most notable thing happening between this line and the next one (Adding illustration) is the initialization of the ZIM creator.

What platform are you on? Which docker version? Not that it should matter but I have no lead at the moment.

`docker system info` gives me `Server Version: 20.10.11`

**Comment by Adam7288** [comment]
Looks like because the file system I was using was mounted as nfs v3, it did not support file locking. Switched to nfs v4 and it worked. Possibly worth investigating supporting nfs v3 file locking. Or a disclaimer. Thanks for helping me work through this.

**Comment by rgaudin** [comment]
Thanks ; glad you found the issue. I'm not sure we'd have much control with the scraper. We've already had issues with docker and NFS with the Zimfarm and ended-up avoiding it.

Looking at [the doc](https://docs.docker.com/storage/volumes/) it seems you may have better luck using the nfs driver.
