### ISSUE TITLE
Support selecting the desired articles by passing a list

### ISSUE THREAD

**Issue by erikos** [openzim/wikihow#110]
Originally the plan was to use a bad list to exclude content we would not like to ship with the wikiHow content. This would mean to go through all of the content and select the inappropriate/not desired one - which has the risk of missing out some of it.

The other way round would be to actually go by a list of articles that should be included. Basically the other way round. This would give full control of what exactly is part of the final zim file. This allows also to apply other curation criteria - like only select articles that are expert reviewed for example.

The flow would be, to provide a "desired articles" list (one article per line) and create the zim file from that. See https://githubhelp.com/openzim/mwoffliner/issues/58

**Comment by rgaudin** [comment]
There are three different issues in here:

- Only including articles from a whitelist is fairly straightforward. We'd assume a similar format as for the blacklist: one article-path per line. `Category:` prefixed includes the whole category (including subcategories), `Category:` prefixed but ending with a `/` doesn't includes the sub categories.
- Expert-reviewed filtering is a completely different feature that could be applied. If you're interested in this, open a separate ticket. I am not sure how easy we get access to this information and if we'd be able to retrieve its list (for the non-whitelist use case).
- Article browsing is currently based on the website being scraped top-bottom, starting either from the homepage or a category.

In the case of a whitelist, the ZIM would have the required articles but there would be no way to browse articles:
- certainly not all articles in the list would have interlinks to go from one article to the other
- no homepage. What would be the homepage? The first article in the list?

We need to decide what we want to do about this. What comes to mind first is a new, built-from-scratch page listing the included articles but it raises a number of design questions and might not be very good looking.

**Comment by erikos** [comment]
The part about the _Expert-reviewed_ filtering was a bit misleading to have added here. We do not need this for now, as this can be done by the ones putting the good list together.

**Comment by rgaudin** [comment]
OK, so the objective is not actually to build the ZIM file from a list of selected articles (as it is done in mwoffliner) but instead to add an additional filter on top of the general one (categories mostly).

As we have the `--exclude` param for excluding found articles, this would introduce a `--only` param.

Scraping would not be altered but addition to ZIM would be conditioned to the presence in the list. The list would **only take articles** and not categories as category-inclusion is already a top-level filter/param.
