### ISSUE TITLE
The "Cars & Other Vehicles" category is not scraping correctly

### ISSUE THREAD

**Issue by dylanmccall** [openzim/wikihow#112]
The "wikihow_en_endless_cars-and-other-vehicles" recipe on farm.openzim.org is producing an empty zim file as output:

https://farm.openzim.org/recipes/wikihow_en_endless_cars-and-other-vehicles

One noteworthy difference between this WikiHow category and others is that this one has a special character in the category name: `Cars-%26-Other-Vehicles`.

**Comment by kelson42** [comment]
@dylanmccall Probably a configuration problem. I will check.

**Comment by kelson42** [comment]
@rgaudin It seems to still fail. Looks like some kind of URL encoding bug, or filtering bug.

**Comment by dylanmccall** [comment]
This looks good now. Thank you!! :)
