### ISSUE TITLE
Remove references to not-included articles

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#114]
With three filtering systems in place: `--category`, `--exclude` and `--only`, there are many ways for a ZIM to point to an article that is not present.

The actual behavior of the ZIM depends on where the _link_ appear and what filtering system was used:

- Category pages keep the article block but remove the `href` from the link. Only hovering over the block can the user understand (pointer icon, no url to go to) this is not a link.
- Related articles blocks in article page would not include missing articles if using an `--only` list.
- Related articles blocks in article page would include broken links to articles if using an `--exclude` list.

This ticket is here to gather expected behavior so we can define what's possible and harmonize. Please suggest.

Note: this will complexify the scraping as we'd need to know (query and store) the list of expected articles.

**Comment by erikos** [comment]
For the category page when an article is not present the card should be removed rather than kept around. For the user it is not obvious why the card is there but not pointing to an article. Even if this is not the same experience as clicking on a link/card and then finding out that the article is not present. At least in this case the user gets some feedback - the article is not present.

**Comment by erikos** [comment]
Yes, we should have a harmonized behavior when there are missing links. The card/block should be removed in this case. For example the article card in the _Category page_ or the card in the _You might also like_ section when the article is not present.

 One thing to note here is that for example for the _Author section_ it would be good to keep that information around. Even though we do not include the authors articles and therefor have the experience you described that the href is removed from the link.

**Comment by rgaudin** [comment]
Thank you; that makes sense

**Comment by erikos** [comment]
When the articles are removed from the category pages and other places will the grid reflow? Or will we have gaps?

**Comment by rgaudin** [comment]
There won't be gaps ; card would move along

**Comment by erikos** [comment]
> There won't be gaps ; card would move along

Perfect! :)
