### ISSUE TITLE
Latest WikiHow in Thai is almost empty

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#124]
See:
![image](https://user-images.githubusercontent.com/1029718/168649058-c8d0f685-2d88-4098-869b-55244e85398d.png)

If you look at https://library.kiwix.org/wikihow_th_maxi_2022-04/, it seems that none of the articles have been scraped!

**Comment by kelson42** [comment]
If I look to the code, it seems that if the HTTP 404 limt is reached, the process does not stop... but just continues:
```
%E0%B8%9E%E0%B8%B9%E0%B8%94%E0%B9%82%E0%B8%99%E0%B9%89%E0%B8%A1%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B9%83%E0%B8%AB%E0%B9%89%E0%B9%81%E0%B8%A1%E0%B9%88%E0%B8%95%E0%B8%AD%E0%B8%9A%E0%B8%95%E0%B8%81%E0%B8%A5%E0%B8%87
[MainThread::2022-04-21 13:33:03,125] WARNING:>>> HTTP 404, skipping.
[MainThread::2022-04-21 13:33:03,127] DEBUG:Maximum HTTP 404 threshold reached (200)
[MainThread::2022-04-21 13:33:05,130] DEBUG:1972/2931
[MainThread::2022-04-21 13:33:05,130] INFO:>> Article
```

**Comment by rgaudin** [comment]
Worked 3 months ago (4GiB). Tested a few of those missing links. Seems to work. Let's reschedule it and see how it goes.

**Comment by kelson42** [comment]
@rgaudin already restarted, bit scraper should stop if too many 404.

**Comment by rgaudin** [comment]
The problem is that many articles ; especially now that we loop on the list of articles returned by the API; are 404 and we have no idea how many should be the threshold if a threshold should be used at all. I am not sure how that feature can be useful.

**Comment by kelson42** [comment]
We probably should make a threshold based on a percentage of failure over the total number of articles.

**Comment by kelson42** [comment]
New run has exactly the same problem https://farm.openzim.org/pipeline/ac55d1ebc98ea2bc2da82826

**Comment by rgaudin** [comment]
Thank you ; it was not network related. the previously successful run happened before the change in articles list building. Fixed.
