### ISSUE TITLE
Missing article on wikiHow DE

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#128]
Bug seems reproducable, see:
* https://farm.openzim.org/pipeline/62b072ebc98ea2bcead0b826/debug
* https://farm.openzim.org/pipeline/291c62ebc98ea2bc50c1a826/debug

I suspect at the end, somhow fails to finish the scraping process.

**Comment by rgaudin** [comment]
It's not a bug, the API is returning an article that is missing (404), as clearly indicated in the log:

```
[MainThread::2022-05-22 17:56:36,786] INFO:>> Article:Bhatura-zubereiten
[MainThread::2022-05-22 17:56:37,065] WARNING:>>> HTTP 404, skipping.
[MainThread::2022-05-22 17:56:37,071] ERROR:Interrupting process due to error: Maximum HTTP 404 threshold reached (0 ~= 0% )
[MainThread::2022-05-22 17:56:37,072] ERROR:Maximum HTTP 404 threshold reached (0 ~= 0% )
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 994, in run
    self.scrape_articles()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 520, in scrape_articles
    self.record_missing_url(to_url(f"/{article}"))
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 705, in record_missing_url
    raise IOError(
OSError: Maximum HTTP 404 threshold reached (0 ~= 0% )
```

You can check [API output](https://de.wikihow.com/api.php?action=query&generator=categorymembers&gcmtitle=Kategorie:Rezepte&gcmtype=page&prop=info&inprop=url&format=json&gcmcontinue=page|424553414e204c41444f4f205a55424552454954454e|67219) ; including a screenshot as this link is pagination-dependent

<img width="960" alt="Screen Shot 2022-05-24 at 09 24 12" src="https://user-images.githubusercontent.com/57929/169998569-e64f5d19-ae23-4a29-9f86-18adaba9f5c6.png">

```sh
curl -I https://de.wikihow.com/Bhatura-zubereiten
HTTP/2 404
```

I suppose we should raise the 404 threshold for that recipe.
