### ISSUE TITLE
Wikihow scrape stuck at the end

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#131]
https://farm.openzim.org/pipeline/244f72ebc98ea2bc6cc5e826/debug

**Comment by rgaudin** [comment]
Nope, the scraper exited with `1` and the reason is visible in the log:

```
[MainThread::2022-05-28 06:57:11,801] INFO:>> Article:Organize-and-Store-Fruit
[MainThread::2022-05-28 06:57:12,074] WARNING:>>> HTTP 404, skipping.
[MainThread::2022-05-28 06:57:12,080] ERROR:Interrupting process due to error: Maximum HTTP 404 threshold reached (0 ~= 0% )
[MainThread::2022-05-28 06:57:12,081] ERROR:Maximum HTTP 404 threshold reached (0 ~= 0% )
```

We'll need to implement #130 ASAP I suppose

**Comment by kelson42** [comment]
Sorry, but I have to reopen the ticket, see https://farm.openzim.org/pipeline/c05ec6889473fadf262c6b26/debug

**Comment by rgaudin** [comment]
Don't be sorry! Though I see no ground for reopening this issue. 

```
INFO:>> Article:Make-Golden-Rum-Cake
WARNING:>>> HTTP 404, skipping.
ERROR:Interrupting process due to error: Maximum HTTP 404 threshold reached (0 ~= 0% )
ERROR:Maximum HTTP 404 threshold reached (0 ~= 0% )
```

We still need #130…

Please reopen if I didn't understand what you meant.
