### ISSUE TITLE
Latest wikiHow (en) has a lot of broken links

### ISSUE THREAD

**Issue by holta** [openzim/wikihow#133]
Regarding: https://download.kiwix.org/zim/wikihow/wikihow_en_maxi_2022-01.zim

It has many broken links.  For example almost 50% of the category links fail when clicking from http://iiab.me/kiwix/wikihow_en_maxi_2022-01/ trying to reach these missing pages:

- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Guitar-Chords-and-Songs
- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Driving-Basics
- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Using-PDF-Files
- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Better-Writing
- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Calculating-Volume-and-Area
- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Death-Funerals-and-Bereavement
- http://iiab.me/kiwix/wikihow_en_maxi_2022-01/Category:Reproductive-Health

@rgaudin would building a new ZIM file with your latest code possibly resolve this?

And if so, do you know why https://farm.openzim.org/recipes/wikihow_en_maxi fails almost every month recently?

**Comment by holta** [comment]
Is this prior issue possibly related?

- #126

**Comment by rgaudin** [comment]
@holta this ZIM is definitely too old and needs to be recreated. Many fixes have been introduced since.

It failed due to #130 which I will address shortly.

**Comment by rgaudin** [comment]
Closing this as a duplicate then ; please subscribe to #130

**Comment by holta** [comment]
Really great news!

Thank you @rgaudin.
