### ISSUE TITLE
wikihow2zim: error: argument --missing-article-tolerance: invalid int value: '1.0'

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#137]
https://farm.openzim.org/pipeline/93611dfe0631cbc8e5884136/debug

**Comment by rgaudin** [comment]
That's a zimfarm issue. Kinda strange we never encountered it elsewhere before. Fixed via https://github.com/openzim/zimfarm/commit/941c9093447676eb8465e3ea5a9584a7df593c5c
