### ISSUE TITLE
css-beautify has been removed

### ISSUE THREAD

**Issue by benoit74** [openzim/wikihow#151]
The scrapper uses `css-beautify` as Python dependency.

It cannot be found anymore in PyPi, and [this page](https://libraries.io/pypi/css-beautify) states that it has been removed, I did not found any other information on the web.

We need a replacement.

**Comment by benoit74** [comment]
Is it possible that it has been renamed [cssbeautifier](https://pypi.org/project/cssbeautifier/) (it was already the Python module name)?

**Comment by benoit74** [comment]
@rgaudin did you already encountered this issue in another scraper?

**Comment by rgaudin** [comment]
We don't use this anywhere else AFAIK. I believe it was used so that we'd get url() on separate lines as we transform them.
