### ISSUE TITLE
wikihow2zim.scraper.DomIntegrityError: #content_wrapper not found

### ISSUE THREAD

**Issue by benoit74** [openzim/wikihow#153]
We need to investigate https://github.com/openzim/zim-requests/issues/797

**Comment by rgaudin** [comment]
This error is in place exactly to warn us when the source DOM changed, because we rely on it.

**Comment by benoit74** [comment]
> This error is in place exactly to warn us when the source DOM changed, because we rely on it.

I imagine, then we have to support the new / different DOM (looks like other recipes are ok, so it might be specific to this language).

**Comment by rgaudin** [comment]
Yes and yes 😐

**Comment by RavanJAltaie** [comment]
@benoit74 is this fixable?

**Comment by benoit74** [comment]
I don't know. Probably yes, but someone (probably me) has to dive into the issue

**Comment by benoit74** [comment]
It is working now ... can't repro ... most probably yet another throttling issue
