### ISSUE TITLE
Include wikiHow: namespace

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#31]
Not sure exactly how we'd be able to get a list of those pages, but it seems that most support pages are on wikiHow: namespace. Ideally, we'd always want to capture this whole namespace (expect if using a `--no-wikihow-ns` option?) to capture those.

Maybe we can't get a list of NS articles and we just recursively fetch what we find in #28 

Same goes for `/Author` profile pages

**Comment by kelson42** [comment]
Do we have important pages to scrape in this namesapce? If "yes" a few examples would be helpful.

**Comment by rgaudin** [comment]
> Do we have important pages to scrape in this namesapce? If "yes" a few examples would be helpful.

As written in the ticket:
> it seems that most support pages are on wikiHow: namespace. 

Those include several links all within that namespace. @kelson42 is there a wiki way to list pages in this namespace ? Search maybe ?

**Comment by kelson42** [comment]
Yes via the API, we do such a call in MWoffliner to get the list of articles.

**Comment by rgaudin** [comment]
Do you happen to know the end-point? So that we can directly look for details on mw.org

**Comment by rgaudin** [comment]
Thank you @kelson42 

For reference:

https://www.mediawiki.org/wiki/API:Allpages#GET_request

```
https://www.wikihow.com/api.php?action=query&format=json&list=allpages&apnamespace=4
```

**Comment by rgaudin** [comment]
Seems like there's way too much ages in that NS for our use case though :/

**Comment by rgaudin** [comment]
We actually don't need it.
