### ISSUE TITLE
Article: reference block style

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#39]
When there are many references, there's a *more references* link to expand. Before clicking that link, the whole block style is not of the right width

<img width="801" alt="Screen Shot 2021-08-24 at 11 12 31" src="https://user-images.githubusercontent.com/57929/130606970-89a64a5e-d41c-4f80-89d5-37fd8bbdedd7.png">

**Comment by fadiga** [comment]
It is fixed
