### ISSUE TITLE
Handle legit 404

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#43]
It seems that (some?) login-only (contribution-related) pages are using a `404` HTTP code.

You can see this in action in [Category:Amusement-and-Theme-Parks](https://www.wikihow.com/Category:Amusement-and-Theme-Parks), clicking the last article link [Write a New Article About Visiting a Theme Park on wikiHow](https://www.wikihow.com/wikiHow:Write-a-New-Article-About-Visiting-a-Theme-Park-on-wikiHow).

This crashes our scraper as would any 404 for articles.

We want to change this behavior as we know we should expect 404 for this use case:

- [ ] Handle 404 errors in `scrape_article`, returning info that we failed to scrape
- [ ] remove link from category page should we failed to scrape
- [ ] Print a log indicating the URL/article that was removed
- [ ] Keep a set of missing URLs
- [ ] Crash should it exceed a certain threshold (50 for now?)
- [ ] Indicate number of missing articles in end-of-scrape stats

⚠️ This currently prevents us from running English (and probably others) to fill-up the optim cache.

**Comment by kelson42** [comment]
FYI With MWoffliner we have a few legit scenarios leading to a HTTP 404. Therefore we allow it, to the contrary to other HTTP errors.

**Comment by rgaudin** [comment]
Yep, that's what I figured. Thanks for confirming this is not unexpected behavior.
