### ISSUE TITLE
Filter out copyrighted material

### ISSUE THREAD

**Issue by Popolechien** [openzim/wikihow#52]
We have permission from the WH folks, with one caveat: we cannot scrape pages with copyrighted material (images). Apparently they're under a specific module so should be fairly easy to parse (it's not too apparent though for a random viewer).

@rgaudin @fadiga Do you need me to reach out to them to have them flag a couple of these?

**Comment by kelson42** [comment]
@Popolechien yes, we need to clearly know the criteria

**Comment by rgaudin** [comment]
Why am I learning about this only now?

**Comment by kelson42** [comment]
Without a clear machine readable way of identifying such content, the implementation of this ticket will have to be postponed.

**Comment by Popolechien** [comment]
Word from WikiHow folks:

"All of the images on our site that are not covered by wikiHow's CC license are marked with this template: https://www.wikihow.com/Template:WikiVisual. The videos on our site are also not released under the CC license"
