### ISSUE TITLE
Filter out sexual and any other inappropriate content

### ISSUE THREAD

**Issue by dsd** [openzim/wikihow#53]
We would like to remove sex-related content and any other content inappropriate for minors.
This likely calls for a blacklist of certain articles and categories.

cc @ramcq

**Comment by kelson42** [comment]
@rgaudin would such a principle workable? for articles? For categories?

**Comment by rgaudin** [comment]
Yes, we can surely add an `--exclude` option that would take a single column file (as we do for our mw selections) with a list of Article or Category paths.

@dsd could either maintain a single large file or per-language list. Should make much difference.

**Comment by kelson42** [comment]
@dsd I propose the following workflow:
* We secure there is a `--exclude` option in the scraper like described 2 comments above by @rgaudin 
* You prepare and maintain the blacklist(s) and publish them online (available via https)
* We will secure dedicated recipes in Zimfarm integrating this blacklist(s)
* We will publish this/these ZIM special flavour of wikiHow in a dedicated online place (like for Wikipedia).

Works for you?

**Comment by kelson42** [comment]
@dsd We are approaching the end of the project. Any news on your side about such blacklists?

**Comment by dsd** [comment]
Thanks for the reminder.
Yes, the above scheme will work just fine. Thanks for making such arrangements.
@dbnicholson please could you suggest an appropriate place where we could host such blacklist.

**Comment by dsd** [comment]
Lets also nail down the setup here. This blacklist will have one entry per line.

Each entry is either:
 1. An article page name (e.g. `Make-Sex-Better`), in which case that article is excluded from the zim
 2. A category name (e.g. `Category:Sexual-Activity`) in which case all of the articles listed under that category, and the category page itself, are all excluded from the zim

Is that right?

Also, I am curious if that will also cause the images included on those pages to be excluded from the zim?

Thanks!

**Comment by rgaudin** [comment]
@dsd, absolutely. Please keep the english `Category:` prefix for all languages. And yes, images from those articles will be excluded as well.

I'll make a demo file so you can test

**Comment by dbnicholson** [comment]
> Thanks for the reminder.
> Yes, the above scheme will work just fine. Thanks for making such arrangements.
> @dbnicholson please could you suggest an appropriate place where we could host such blacklist.

Sure, we can just throw them in an S3 bucket. If you don't care about the URL, that's all that's needed. If you want a nicer domain, we can put a CDN in front of it.

**Comment by kelson42** [comment]
@dbnicholson We would appreciate a persistent/stable http or https link.

**Comment by dbnicholson** [comment]
They're persistent in S3. The difference is the domain isn't as pretty since it would be something like https://wikihow-denylists.s3.amazonaws.com. But I don't know what neutral domain is available for this. If you or someone else can manage the wikihow.com DNS we can put a CDN in front of it with a domain like https://denylists.wikihow.com.

**Comment by kelson42** [comment]
@dbnicholson It can be a "random" URL. No problem, because this is an internal thing. We can the keep the native S3 URL.

**Comment by dsd** [comment]
Thanks. The URL to use is https://s3.amazonaws.com/endlessm-storage/kiwix/wikihow-blocklist.txt
Added 2 sample entries, we will add more when we have a chance.

**Comment by rgaudin** [comment]
👍

**Comment by kelson42** [comment]
@dsd Thx, this is a good start for wikiHow in English. Feel free to make other files for wikiHow in other languages - if needed.

**Comment by manuq** [comment]
Nit: can this be called "badlist" instead of "blacklist" ?
