### ISSUE TITLE
Full text search unavailable

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#59]
Both searches are unavailable at: http://dev.library.kiwix.org/wikihow_eng_all_2021-08/C/Main-Page.

I get the suggestions but nothing happens when I click on an item

**Comment by rgaudin** [comment]
only old kiwix serve has this bug.

**Comment by kelson42** [comment]
ok, still a bit worried about that... @mgautierfr anything which can be done abpit that?

**Comment by rgaudin** [comment]
Given we get the list right, it's probably a UI issue : css or script conflicting with kiwix serve's toolbar (already raised the iframe issue enough 😉).
that's looking at this that I found the jquery error in console on latest kiwix serve.

**Comment by kelson42** [comment]
actually only suggestions work with cutting edge kiwix serve.

**Comment by rgaudin** [comment]
OK, this was a libzim version issue. Running it with the latest one we built fixed it:

<img width="920" alt="Screen Shot 2021-09-06 at 13 37 58" src="https://user-images.githubusercontent.com/57929/132225760-63882154-f07e-40f5-a704-38d525974fae.png">

https://dev.library.kiwix.org/search?content=wikihow_id_selection_2021-09&pattern=sepatu+
