### ISSUE TITLE
WikiHow in japanese as an other URL structure

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#62]
We could have thought thst this would be https://jp.wikihow.com... but it is https://wikihow.jp.

Therefore, this version of wikiHow seems not scrapable yet.

**Comment by kelson42** [comment]
For Farsi, this is wikihowfarsi.com

**Comment by rgaudin** [comment]
Japanese language code is `ja`, as show in `--help`. Please RTFM :)

**Comment by kelson42** [comment]
wikihow.com.tr for turkish

**Comment by rgaudin** [comment]
Can you please stop ?

**Comment by kelson42** [comment]
wikihow.cz for czeck

**Comment by rgaudin** [comment]
OK, I'm unsubscribing from this
