### ISSUE TITLE
Footer: Put links at the same vertical level like the logo

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#69]
This looks pretty weird and does not optimize the space usage of the screen
![image](https://user-images.githubusercontent.com/1029718/132460453-b52441b3-8e96-4ac7-84e5-63b81ca56499.png)

**Comment by rgaudin** [comment]
That version didn't have the bread crumbs that appear on top of that separation line. With them, and the links atop, it will be very packed.

Also, I don't think it looks weird. Kinda subjective obviously.

As for space optimization, this is the very bottom of the screen… and it looks different on mobile.

Finally, I'd prefer us not to meddle with wikiHow's UI unless necessary.

I'd suggest we close that and wait for our main user's feedback. If it bothers them, then we can change it.
