### ISSUE TITLE
Remove page views number

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#72]
![image](https://user-images.githubusercontent.com/1029718/132463367-ca7058ab-ba5c-4eda-89b3-4e50b1b7fa06.png)

To me tha added value online is questionable... but offline, this does not make sense. I would just delete it.

**Comment by rgaudin** [comment]
We kept it on purpose in sotoki but there the notion of DB dump is slightly more explicit. It's the main indicator of popularity so it is important but as always, this is misleading offline. I have no opinion on this. @Popolechien

**Comment by Popolechien** [comment]
We can keep it as hidden if this helps sorting / displaying solutions on the front page, but otherwise I see no point in displaying a stale number.

**Comment by rgaudin** [comment]
OK, let's remove it then.
