### ISSUE TITLE
Images/Videos should have meaningfull names

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#73]
This does not ease the re-usage of the content and is not necessary (we don't deal with so many files in this scraper). We should keep the original filename.

**Comment by rgaudin** [comment]
It's not possible to guarantee meaningful names.

We can surely reuse original filenames. At least Step photos mostly have descriptive names: `v4-728px-Celebrate-Father%27s-Day-Step-1.jpg`

Or we can slugify `<img />`'s `alt` attribute, when present: `image-intitulee-celebrate-father-s-day-step-1`.

Please advise.

**Comment by kelson42** [comment]
I advise to take the original filename.
