### ISSUE TITLE
Better handling of picture source

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#76]
[Source element](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Source) can be quite complex as its role is to help the browser choose the most appropriate source for a `<picture />`, `<video />` or `<audio />`.

It is apparently sometimes used in WikiHow. Example use is the WH avatar on top of [Cook-Chips-in-an-Airfryer](https://www.wikihow.com/Cook-Chips-in-an-Airfryer)

For the sake of the ZIM filesize, we should:
- find out the appropriate URL of a `<picture />` image
- Keep only a single `<source />` or `<img />` element with our optimized version.
- remove the rest.

Current behavior ignore those and thus only handles the `<img />` fallback that's always included so that's what the browser picks. But it would be cleaner to remove this extra source code.

**Comment by kelson42** [comment]
Following my experience with MWoffliner, it might need a bit of logic to find the appropriate source. Important is that the video file resolution is not a lot lower than the display resolutuon.

**Comment by rgaudin** [comment]
This ticket is about picture (see the title), not video. For picture, it is used apparently when wikiHow offers WebP with a fallback. There doesn't appear to be multiple resolutions but that's what needs to be checked in the ticket.

**Comment by rgaudin** [comment]
Tests converge to the initial assessment: it's only a way to offer webP. We're using (converting) the fallback and removing the rest. Good enough.
