### ISSUE TITLE
Videos on iOS not working

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#83]
Here at http://dev.library.kiwix.org/wikihow_fr_all_2021-09/c%C3%A9l%C3%A9brer-le-Nouvel-An-chinois

![7EA03DF4-529A-47F2-9697-DDB4BD748B82](https://user-images.githubusercontent.com/1029718/132949637-4eb9341b-8bf4-41ae-8f3f-943974ea2a69.png)

**Comment by kelson42** [comment]
Here an other page with two occurrences of this bug:
http://dev.library.kiwix.org/wikihow_fr_all_2021-09/am%C3%A9liorer-son-temps-au-1-600-m%C3%A8tres

**Comment by kelson42** [comment]
Might be a problem specific to iPad as videos seems not playable on my iPad. See here for example

![B1E1DC8F-9654-4035-A24F-611B9D457017](https://user-images.githubusercontent.com/1029718/132949959-d3e8f636-b82f-414e-bc69-79c36b700bfb.png)

**Comment by rgaudin** [comment]
I don't remember we specifically tested videos on iOS. Might be the issue.

**Comment by rgaudin** [comment]
Was fixed in  #75 actually (WASM files needs a specific mimetype) but Safari displays some controls on those videos which is not visually OK so leaving it open for that.

**Comment by rgaudin** [comment]
It seems we can't remove it as it's added on purpose by the browser. As the visual impact is limited, I'm closing it. We can revisit that in the future if Safari policy evolves or someone finds a way.

**In Firefox**
<img width="900" alt="Screen Shot 2021-09-15 at 14 44 31" src="https://user-images.githubusercontent.com/57929/133455594-0f6ea5ca-2734-42af-bf53-1808be822258.png">

**In Safari**
<img width="967" alt="saf" src="https://user-images.githubusercontent.com/57929/133455785-99cd0a71-56e9-4572-9861-41d6d7590dbb.png">

**In related**
<img width="1123" alt="rel" src="https://user-images.githubusercontent.com/57929/133455800-7a34f888-b166-472a-9f4c-47a860fffa6b.png">

**Comment by kelson42** [comment]
On my iPad,  the very same problem os still although anew wikiHow ZIM file has been prepared 2 days ago.

![182A32F7-4585-45B2-88BA-1B538DB7C448](https://user-images.githubusercontent.com/1029718/134779944-c4b4244c-3fc9-41ad-b171-17136b81664a.png)

**Comment by rgaudin** [comment]
iOS or iPadOS version please

**Comment by kelson42** [comment]
Ipados 14.7.1

**Comment by kelson42** [comment]
Upgraded to ipados 15.0. Which shoukd have webm support in safari... but same problem with both ff anf safari.

**Comment by kelson42** [comment]
Same bug (or related to) as https://github.com/openzim/youtube/issues/34.

**Comment by rgaudin** [comment]
> Upgraded to ipados 15.0. Which shoukd have webm support in safari... but same problem with both ff anf safari.

Hum, no. It's not supported in iOS15. Some *WebM audio* stuff got in but not the video as we want it. Fixing it though as it's a scraper issue

**Comment by kelson42** [comment]
I believe the problem is not fully fixed, yesterday I came again a similar proble, but symptom slightly different:
![image](https://user-images.githubusercontent.com/1029718/135578478-39224780-c7ac-428c-8a1f-58e813ffb12a.png)

at https://dev.library.kiwix.org/wikihow_de_all_2021-09/meta

**Comment by rgaudin** [comment]
Thanks @kelson42  ; I'm about to open a new ticket as to keep this one more focused
