### ISSUE TITLE
Blank space in related links

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#85]
Here for example: http://dev.library.kiwix.org/wikihow_fr_all_2021-09/devenir-un-bon-coureur#Am.C3.A9liorer-la-vitesse-et-la-puissance

![D7693305-3CE8-49A9-AA44-77B289020DB9](https://user-images.githubusercontent.com/1029718/132949797-58eb1e82-9d4d-4309-9204-f02c6526aa08.png)

in comparison to original page: https://fr.wikihow.com/devenir-un-bon-coureur

![770876BE-98BD-4006-9263-7F26D19DCE0F](https://user-images.githubusercontent.com/1029718/132949815-6459b73e-2927-4062-ace0-db410952ae26.png)

**Comment by rgaudin** [comment]
There's no missing related. It's shifted one space. I remember we've seen that while implementing videos.
