### ISSUE TITLE
Article thumbnails in category pages are missing titles

### ISSUE THREAD

**Issue by dylanmccall** [openzim/wikihow#88]
In the wikihow zim file, it is possible to browse to a category page, such as http://dev.library.kiwix.org/wikihow_eng_all_2021-08/C/Category:Arts-and-Entertainment. A category page contains a long list of articles. However, the articles in this list are shown only as images. Their titles are not visible:

![Screenshot from 2021-09-14 09-02-56](https://user-images.githubusercontent.com/132063/133293403-c6c127e3-8645-42a8-aa9b-379314c1abbc.png)

It looks like the titles _are_ available in the HTML here. For example, the first of those images looks like this:

```html
<div class="responsive_thumb">
<a href="./Be-Talented-in-Multiple-Areas">
<div class="content-spacer">
<img class="content-fill" id="612e7c2e76e5c" src="./images/1870675199" width="375" height="321">
</div>
<div class="responsive_thumb_title">
<span>How to</span>
<p>Be Talented in Multiple Areas</p>
</div>
</a>
<div class="cat_expert">Expert</div>
</div>
```

However, some CSS is causing `.content-spacer` to overlap `.responsive_thumb_title`.

**Comment by rgaudin** [comment]
Yep, we had that with English. Pretty sure it's been fixed but we haven't recreated the ZIM for English. Will do.
