### ISSUE TITLE
Many categories are missing in wikiHow TH

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#94]
This is visible from the welcome page. Following links are 404:
* http://dev.library.kiwix.org/wikihow_th_all_2021-09/%E0%B8%AB%E0%B8%A1%E0%B8%A7%E0%B8%94%E0%B8%AB%E0%B8%A1%E0%B8%B9%E0%B9%88:%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B9%E0%B9%81%E0%B8%A5%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B9%80%E0%B8%AD%E0%B8%87%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%A3%E0%B8%AA%E0%B8%99%E0%B8%B4%E0%B8%A2%E0%B8%A1%E0%B8%AA%E0%B9%88%E0%B8%A7%E0%B8%99%E0%B8%95%E0%B8%B1%E0%B8%A7
* http://dev.library.kiwix.org/wikihow_th_all_2021-09/%E0%B8%AB%E0%B8%A1%E0%B8%A7%E0%B8%94%E0%B8%AB%E0%B8%A1%E0%B8%B9%E0%B9%88:%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%9E%E0%B8%B1%E0%B8%99%E0%B8%98%E0%B9%8C

**Comment by rgaudin** [comment]
https://farm.openzim.org/pipeline/0d8079bb61c325327dfe6316
